/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */import java.sql.*;
 import javax.swing.JOptionPane;
public class Dresses_Jumpsuits extends javax.swing.JFrame {

    /**
     * Creates new form Dresses_Jumpsuits
     */
    public Dresses_Jumpsuits() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        r9 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        r7 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        r4 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        r1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        r14 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        r13 = new javax.swing.JRadioButton();
        r15 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        r10 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        r11 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(884, 456));
        setMinimumSize(new java.awt.Dimension(884, 456));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(884, 878));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(884, 878));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(884, 878));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(884, 878));
        jPanel1.setMinimumSize(new java.awt.Dimension(884, 878));
        jPanel1.setPreferredSize(new java.awt.Dimension(884, 878));
        jPanel1.setLayout(null);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(240, 240, 240));
        jLabel33.setText("Women Red Printed Flare Dress");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(610, 370, 220, 20);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(240, 240, 240));
        jLabel29.setText(" Rs. 2999(Incl. of all taxes)");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(610, 390, 220, 20);

        buttonGroup3.add(r9);
        r9.setForeground(new java.awt.Color(240, 240, 240));
        r9.setText("L");
        jPanel1.add(r9);
        r9.setBounds(710, 420, 31, 23);

        buttonGroup3.add(r8);
        r8.setForeground(new java.awt.Color(240, 240, 240));
        r8.setText("M");
        jPanel1.add(r8);
        r8.setBounds(680, 420, 33, 23);

        buttonGroup1.add(r2);
        r2.setForeground(new java.awt.Color(240, 240, 240));
        r2.setText("M");
        jPanel1.add(r2);
        r2.setBounds(120, 430, 33, 23);

        buttonGroup1.add(r3);
        r3.setForeground(new java.awt.Color(240, 240, 240));
        r3.setText("L");
        jPanel1.add(r3);
        r3.setBounds(150, 430, 31, 23);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(240, 240, 240));
        jLabel25.setText("Size");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(610, 420, 30, 20);

        buttonGroup3.add(r7);
        r7.setForeground(new java.awt.Color(240, 240, 240));
        r7.setText("S");
        r7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7ActionPerformed(evt);
            }
        });
        jPanel1.add(r7);
        r7.setBounds(650, 420, 31, 23);

        buttonGroup2.add(r5);
        r5.setForeground(new java.awt.Color(240, 240, 240));
        r5.setText("M");
        jPanel1.add(r5);
        r5.setBounds(400, 430, 33, 23);

        buttonGroup2.add(r6);
        r6.setForeground(new java.awt.Color(240, 240, 240));
        r6.setText("L");
        jPanel1.add(r6);
        r6.setBounds(430, 430, 31, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/J3.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 114, 194, 259);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/J5.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(610, 114, 176, 250);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(240, 240, 240));
        jLabel24.setText("Size");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(330, 430, 30, 20);

        jButton2.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton2.setText("Add to Cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(480, 430, 100, 25);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(240, 240, 240));
        jLabel27.setText("Women Green Printed Fit and Flare Dress");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(320, 380, 280, 20);

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("JUMPSUITS");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(319, 26, 230, 51);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jLabel28.setText(" Price Rs. 2099 (Incl. of all taxes)");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(320, 400, 240, 20);

        buttonGroup2.add(r4);
        r4.setForeground(new java.awt.Color(240, 240, 240));
        r4.setText("S");
        jPanel1.add(r4);
        r4.setBounds(370, 430, 31, 23);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText(" Rs. 3299(Incl. of all taxes)");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(50, 399, 220, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Black Solid Basic Jumpsuit");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(50, 379, 210, 20);

        jButton1.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 430, 100, 25);

        jButton7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton7.setText("Cart");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(630, 40, 90, 27);

        jButton3.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton3.setText("Add to Cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(760, 420, 100, 25);

        buttonGroup1.add(r1);
        r1.setForeground(new java.awt.Color(240, 240, 240));
        r1.setText("S");
        jPanel1.add(r1);
        r1.setBounds(90, 430, 31, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/J2.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 114, 194, 259);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText(" Price Rs. 1599 (Incl. of all taxes)");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(550, 770, 240, 23);

        buttonGroup5.add(r14);
        r14.setForeground(new java.awt.Color(240, 240, 240));
        r14.setText("M");
        jPanel1.add(r14);
        r14.setBounds(620, 800, 33, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/J1.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(550, 470, 194, 260);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(240, 240, 240));
        jLabel32.setText("Women Teal Blue Printed Fit & Flare Dress");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(550, 750, 290, 20);

        buttonGroup5.add(r13);
        r13.setForeground(new java.awt.Color(240, 240, 240));
        r13.setText("S");
        jPanel1.add(r13);
        r13.setBounds(590, 800, 31, 23);

        buttonGroup5.add(r15);
        r15.setForeground(new java.awt.Color(240, 240, 240));
        r15.setText("L");
        jPanel1.add(r15);
        r15.setBounds(650, 800, 31, 23);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Size");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(550, 800, 40, 20);

        jButton5.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton5.setText("Add to Cart");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(700, 800, 100, 25);

        jButton6.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton6.setText("Add to Cart");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(340, 800, 100, 25);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(240, 240, 240));
        jLabel35.setText(" Price Rs. 3099 (Incl. of all taxes)");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(190, 770, 240, 23);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(240, 240, 240));
        jLabel30.setText("Navy Blue Solid Basic Jumpsuit");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(190, 750, 230, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/J4.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 480, 194, 259);

        buttonGroup4.add(r10);
        r10.setForeground(new java.awt.Color(240, 240, 240));
        r10.setText("S");
        jPanel1.add(r10);
        r10.setBounds(230, 800, 31, 23);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("Size");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(190, 800, 40, 20);

        buttonGroup4.add(r11);
        r11.setForeground(new java.awt.Color(240, 240, 240));
        r11.setText("M");
        jPanel1.add(r11);
        r11.setBounds(260, 800, 33, 23);

        buttonGroup4.add(r12);
        r12.setForeground(new java.awt.Color(240, 240, 240));
        r12.setText("L");
        jPanel1.add(r12);
        r12.setBounds(290, 800, 31, 23);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Size");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 430, 27, 20);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code = "", item_name = "", size = "", type = "", price = "", sql;

            sql = "select * from products where i_code=204;";
            System.out.print(sql);

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");

            }

            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);

            if (r10.isSelected()) {
                size = "S";
            }
            if (r11.isSelected()) {
                size = "M";
            }
            if (r12.isSelected()) {
                size = "L";
            }

            sql = "Insert into cart Values(" + i_code1 + ",'" + item_name + "','" + type + "','" + size + "'," + price1 + ");";
            System.out.print(sql);
            st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        } 
        JOptionPane.showMessageDialog(this,"This item has been added to your cart");// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code = "", item_name = "", size = "", type = "", price = "", sql;

            sql = "select * from products where i_code=205;";
            System.out.print(sql);

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");

            }

            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);

            if (r13.isSelected()) {
                size = "S";
            }
            if (r14.isSelected()) {
                size = "M";
            }
            if (r15.isSelected()) {
                size = "L";
            }

            sql = "Insert into cart Values(" + i_code1 + ",'" + item_name + "','" + type + "','" + size + "'," + price1 + ");";
            System.out.print(sql);
            st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        } 
        JOptionPane.showMessageDialog(this,"This item has been added to your cart");// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code = "", item_name = "", size = "", type = "", price = "", sql;

            sql = "select * from products where i_code=203;";
            System.out.print(sql);

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");

            }

            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);

            if (r7.isSelected()) {
                size = "S";
            }
            if (r8.isSelected()) {
                size = "M";
            }
            if (r9.isSelected()) {
                size = "L";
            }

            sql = "Insert into cart Values(" + i_code1 + ",'" + item_name + "','" + type + "','" + size + "'," + price1 + ");";
            System.out.print(sql);
            st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        JOptionPane.showMessageDialog(this,"This item has been added to your cart");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code = "", item_name = "", size = "", type = "", price = "", sql;

            sql = "select * from products where i_code=202;";
            System.out.print(sql);

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");

            }

            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);

            if (r4.isSelected()) {
                size = "S";
            }
            if (r5.isSelected()) {
                size = "M";
            }
            if (r6.isSelected()) {
                size = "L";
            }

            sql = "Insert into cart Values(" + i_code1 + ",'" + item_name + "','" + type + "','" + size + "'," + price1 + ");";
            System.out.print(sql);
            st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
        JOptionPane.showMessageDialog(this,"This item has been added to your cart");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void r7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code = "", item_name = "", size = "", type = "", price = "", sql;

            sql = "select * from products where i_code=201;";
            System.out.print(sql);

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");

            }

            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);

            if (r1.isSelected()) {
                size = "S";
            }
            if (r2.isSelected()) {
                size = "M";
            }
            if (r3.isSelected()) {
                size = "L";
            }

            sql = "Insert into cart Values(" + i_code1 + ",'" + item_name + "','" + type + "','" + size + "'," + price1 + ");";
            System.out.print(sql);
            st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
JOptionPane.showMessageDialog(this,"This item has been added to your cart");        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
billing_section obj = new billing_section();
obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dresses_Jumpsuits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dresses_Jumpsuits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dresses_Jumpsuits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dresses_Jumpsuits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Dresses_Jumpsuits().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r13;
    private javax.swing.JRadioButton r14;
    private javax.swing.JRadioButton r15;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    // End of variables declaration//GEN-END:variables
}
