
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class jackets_coats1 extends javax.swing.JFrame {

    /**
     * Creates new form jackets_coats1
     */
    public jackets_coats1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rb7 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        rb9 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        rb11 = new javax.swing.JRadioButton();
        rb12 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(836, 435));
        setMinimumSize(new java.awt.Dimension(836, 435));
        setPreferredSize(new java.awt.Dimension(836, 435));
        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(822, 816));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(822, 816));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(822, 816));

        jPanel1.setBackground(new java.awt.Color(118, 104, 104));
        jPanel1.setMaximumSize(new java.awt.Dimension(822, 816));
        jPanel1.setMinimumSize(new java.awt.Dimension(822, 816));
        jPanel1.setPreferredSize(new java.awt.Dimension(822, 816));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 99, 198, 235);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 1033, 0, 252);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b2.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(530, 110, 210, 220);

        jButton23.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton23.setText("Add to Cart");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);
        jButton23.setBounds(170, 390, 90, 25);

        jButton25.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton25.setText("Add to Cart");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton25);
        jButton25.setBounds(670, 390, 90, 25);

        jButton26.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton26.setText("Add to Cart");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton26);
        jButton26.setBounds(430, 750, 91, 25);

        jButton27.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton27.setText("Add to Cart");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton27);
        jButton27.setBounds(420, 390, 90, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Navy Blue colourblocked bomber");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 340, 240, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Men Navy Blue & Black Self Design Slim fit Blazer");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(280, 700, 350, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Black woven coat");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(290, 340, 130, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 110, 210, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b3.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 440, 200, 249);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Men Grey Slim Fit Casual Blazer");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(530, 340, 230, 20);

        buttonGroup1.add(r1);
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("S");
        jPanel1.add(r1);
        r1.setBounds(60, 390, 31, 23);

        buttonGroup1.add(r2);
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("M");
        jPanel1.add(r2);
        r2.setBounds(90, 390, 33, 23);

        buttonGroup1.add(r3);
        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.setText("L");
        jPanel1.add(r3);
        r3.setBounds(120, 390, 31, 23);

        buttonGroup2.add(rb4);
        rb4.setForeground(new java.awt.Color(255, 255, 255));
        rb4.setText("S");
        jPanel1.add(rb4);
        rb4.setBounds(320, 390, 31, 23);

        buttonGroup2.add(rb5);
        rb5.setForeground(new java.awt.Color(255, 255, 255));
        rb5.setText("M");
        jPanel1.add(rb5);
        rb5.setBounds(350, 390, 33, 23);

        buttonGroup2.add(rb6);
        rb6.setForeground(new java.awt.Color(255, 255, 255));
        rb6.setText("L");
        jPanel1.add(rb6);
        rb6.setBounds(380, 390, 31, 23);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price Rs 2000 Incl. of all taxes");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 360, 210, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Price Rs 2500 Incl. of all taxes");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(290, 360, 210, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Price Rs 4000 Incl. of all taxes");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(530, 360, 220, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Price Rs 4500 Incl. of all taxes");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(280, 720, 220, 20);

        buttonGroup3.add(rb7);
        rb7.setForeground(new java.awt.Color(255, 255, 255));
        rb7.setText("S");
        jPanel1.add(rb7);
        rb7.setBounds(560, 390, 31, 23);

        buttonGroup3.add(rb8);
        rb8.setForeground(new java.awt.Color(255, 255, 255));
        rb8.setText("M");
        jPanel1.add(rb8);
        rb8.setBounds(590, 390, 33, 23);

        buttonGroup3.add(rb9);
        rb9.setForeground(new java.awt.Color(255, 255, 255));
        rb9.setText("L");
        jPanel1.add(rb9);
        rb9.setBounds(620, 390, 31, 23);

        buttonGroup4.add(rb10);
        rb10.setForeground(new java.awt.Color(255, 255, 255));
        rb10.setText("S");
        jPanel1.add(rb10);
        rb10.setBounds(320, 750, 31, 23);

        buttonGroup4.add(rb11);
        rb11.setForeground(new java.awt.Color(255, 255, 255));
        rb11.setText("M");
        jPanel1.add(rb11);
        rb11.setBounds(350, 750, 33, 23);

        buttonGroup4.add(rb12);
        rb12.setForeground(new java.awt.Color(255, 255, 255));
        rb12.setText("L");
        jPanel1.add(rb12);
        rb12.setBounds(380, 750, 31, 23);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JACKETS AND COATS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 20, 420, 49);

        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setText("Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 30, 90, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Size");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(530, 390, 30, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Size");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(290, 390, 30, 20);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Size");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(280, 750, 30, 20);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Size");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 390, 30, 20);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 820, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
try{
Class.forName("java.sql.DriverManager");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp","root","");
String i_code="",item_name="",sql ,size="",price="",type="";

sql="select * from products where i_code = 106;";
//System.out.print(sql);
Statement st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
if(!rs.next())
    JOptionPane.showMessageDialog(null,"no such record");
else{

i_code=rs.getString("i_code");
item_name=rs.getString("item_name");
price=rs.getString("price");
type=rs.getString("type");
}
int price1=Integer.parseInt(price);

int i_code1=Integer.parseInt(i_code);
if(r1.isSelected())
    size="S";
if(r2.isSelected())
    size="M";
if(r3.isSelected())
    size="L";
sql="insert into cart values ("+i_code1+", '"+item_name+"','"+type+"','"+size+"',"+price1+");";
System.out.print(sql);
st.executeUpdate(sql);


}    
catch(Exception e)
{  JOptionPane.showMessageDialog(null,"Error"+e.getMessage());

}JOptionPane.showMessageDialog(this,"This item has been added to your cart");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
  try{
Class.forName("java.sql.DriverManager");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp","root","");
String i_code="",item_name="",sql ,size="",price="",type="";

sql="select * from products where i_code = 107;";
//System.out.print(sql);
Statement st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
if(!rs.next())
    JOptionPane.showMessageDialog(null,"no such record");
else{

i_code=rs.getString("i_code");
item_name=rs.getString("item_name");
price=rs.getString("price");
type=rs.getString("type");
}
int price1=Integer.parseInt(price);

int i_code1=Integer.parseInt(i_code);
if(rb4.isSelected())
    size="S";
if(rb5.isSelected())
    size="M";
if(rb6.isSelected())
    size="L";
sql="insert into cart values ("+i_code1+", '"+item_name+"','"+type+"','"+size+"',"+price1+");";
System.out.print(sql);
st.executeUpdate(sql);


}    
catch(Exception e)
{  JOptionPane.showMessageDialog(null,"Error"+e.getMessage());

}JOptionPane.showMessageDialog(this,"This item has been added to your cart");             // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
try{
Class.forName("java.sql.DriverManager");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp","root","");
String i_code="",item_name="",sql ,size="",price="",type="";

sql="select * from products where i_code = 108;";
//System.out.print(sql);
Statement st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
if(!rs.next())
    JOptionPane.showMessageDialog(null,"no such record");
else{

i_code=rs.getString("i_code");
item_name=rs.getString("item_name");
price=rs.getString("price");
type=rs.getString("type");
}
int price1=Integer.parseInt(price);

int i_code1=Integer.parseInt(i_code);
if(rb7.isSelected())
    size="S";
if(rb8.isSelected())
    size="M";
if(rb9.isSelected())
    size="L";
sql="insert into cart values ("+i_code1+", '"+item_name+"','"+type+"','"+size+"',"+price1+");";
System.out.print(sql);
st.executeUpdate(sql);


}    
catch(Exception e)
{  JOptionPane.showMessageDialog(null,"Error"+e.getMessage());

}JOptionPane.showMessageDialog(this,"This item has been added to your cart");               // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
try{
Class.forName("java.sql.DriverManager");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp","root","");
String i_code="",item_name="",sql ,size="",price="",type="";

sql="select * from products where i_code = 109;";
//System.out.print(sql);
Statement st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
if(!rs.next())
    JOptionPane.showMessageDialog(null,"no such record");
else{

i_code=rs.getString("i_code");
item_name=rs.getString("item_name");
price=rs.getString("price");
type=rs.getString("type");
}
int price1=Integer.parseInt(price);

int i_code1=Integer.parseInt(i_code);
if(rb10.isSelected())
    size="S";
if(rb11.isSelected())
    size="M";
if(rb12.isSelected())
    size="L";
sql="insert into cart values ("+i_code1+", '"+item_name+"','"+type+"','"+size+"',"+price1+");";
System.out.print(sql);
st.executeUpdate(sql);


}    
catch(Exception e)
{  JOptionPane.showMessageDialog(null,"Error"+e.getMessage());

}JOptionPane.showMessageDialog(this,"This item has been added to your cart");               // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
billing_section obj=new billing_section();
obj.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jackets_coats1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jackets_coats1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jackets_coats1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jackets_coats1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new jackets_coats1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb11;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    // End of variables declaration//GEN-END:variables
}
