/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */import java.sql.*;
 import javax.swing.JOptionPane;
public class Jeans_Jeggings extends javax.swing.JFrame {

    /**
     * Creates new form Jeans_Jeggings
     */
    public Jeans_Jeggings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        r1 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r7 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        r9 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        r13 = new javax.swing.JRadioButton();
        r14 = new javax.swing.JRadioButton();
        r15 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        r10 = new javax.swing.JRadioButton();
        r11 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(867, 445));
        setMinimumSize(new java.awt.Dimension(867, 445));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(877, 832));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(877, 832));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(877, 832));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(877, 832));
        jPanel1.setMinimumSize(new java.awt.Dimension(877, 832));
        jPanel1.setPreferredSize(new java.awt.Dimension(877, 832));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WJ1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 90, 175, 250);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WJ2.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(570, 90, 194, 259);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WJ3.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 90, 194, 259);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WJ5.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(500, 450, 188, 269);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WJ4.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 450, 194, 259);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 0, 0);

        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(133, 1534, 40, 14);

        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(701, 1514, 40, 14);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Women Blue Cropped Jeans");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 350, 230, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Women Blue Stretchable Jeans");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(290, 350, 240, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Women Blue Solid Denim Jeggings");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(570, 360, 260, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" Price Rs. 2500 (Incl. of all taxes)");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(40, 370, 250, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" Price Rs. 1700 (Incl. of all taxes)");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(290, 370, 250, 20);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" Price Rs. 2000 (Incl. of all taxes)");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(580, 380, 250, 20);

        jButton1.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 400, 90, 25);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Size");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(40, 400, 30, 20);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Size");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(580, 410, 30, 20);

        jButton2.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton2.setText("Add to Cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(750, 410, 90, 25);

        jButton3.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton3.setText("Add to Cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(460, 400, 90, 25);

        buttonGroup1.add(r1);
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("S");
        jPanel1.add(r1);
        r1.setBounds(80, 400, 31, 23);

        buttonGroup2.add(r4);
        r4.setForeground(new java.awt.Color(255, 255, 255));
        r4.setText("S");
        jPanel1.add(r4);
        r4.setBounds(350, 400, 31, 23);

        buttonGroup3.add(r7);
        r7.setForeground(new java.awt.Color(255, 255, 255));
        r7.setText("S");
        jPanel1.add(r7);
        r7.setBounds(620, 410, 40, 23);

        buttonGroup1.add(r2);
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("M");
        jPanel1.add(r2);
        r2.setBounds(110, 400, 33, 23);

        buttonGroup1.add(r3);
        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.setText("L");
        jPanel1.add(r3);
        r3.setBounds(140, 400, 31, 23);

        buttonGroup2.add(r6);
        r6.setForeground(new java.awt.Color(255, 255, 255));
        r6.setText("L");
        jPanel1.add(r6);
        r6.setBounds(410, 400, 31, 23);

        buttonGroup2.add(r5);
        r5.setForeground(new java.awt.Color(255, 255, 255));
        r5.setText("M");
        jPanel1.add(r5);
        r5.setBounds(380, 400, 33, 23);

        buttonGroup3.add(r8);
        r8.setForeground(new java.awt.Color(255, 255, 255));
        r8.setText("M");
        jPanel1.add(r8);
        r8.setBounds(660, 410, 40, 23);

        buttonGroup3.add(r9);
        r9.setForeground(new java.awt.Color(255, 255, 255));
        r9.setText("L");
        jPanel1.add(r9);
        r9.setBounds(700, 410, 30, 23);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Size");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(310, 400, 30, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Women Blue Stretchable Jeggings");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(200, 720, 260, 20);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(" Price Rs. 2200 (Incl. of all taxes)");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(200, 740, 250, 20);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Women Blue Haut Skinny Jeans");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(500, 730, 240, 20);
        jPanel1.add(jLabel24);
        jLabel24.setBounds(711, 782, 0, 0);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(" Price Rs. 3900 (Incl. of all taxes)");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(500, 750, 250, 20);

        jButton4.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton4.setText("Add to Cart");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(660, 780, 90, 25);

        buttonGroup5.add(r13);
        r13.setForeground(new java.awt.Color(255, 255, 255));
        r13.setText("S");
        jPanel1.add(r13);
        r13.setBounds(550, 780, 31, 23);

        buttonGroup5.add(r14);
        r14.setForeground(new java.awt.Color(255, 255, 255));
        r14.setText("M");
        jPanel1.add(r14);
        r14.setBounds(580, 780, 33, 23);

        buttonGroup5.add(r15);
        r15.setForeground(new java.awt.Color(255, 255, 255));
        r15.setText("L");
        jPanel1.add(r15);
        r15.setBounds(610, 780, 31, 23);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Size");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(500, 780, 30, 20);

        jlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlabel.setForeground(new java.awt.Color(255, 255, 255));
        jlabel.setText("Size");
        jPanel1.add(jlabel);
        jlabel.setBounds(200, 770, 30, 20);

        buttonGroup4.add(r10);
        r10.setForeground(new java.awt.Color(255, 255, 255));
        r10.setText("S");
        jPanel1.add(r10);
        r10.setBounds(250, 770, 31, 23);

        buttonGroup4.add(r11);
        r11.setForeground(new java.awt.Color(255, 255, 255));
        r11.setText("M");
        jPanel1.add(r11);
        r11.setBounds(280, 770, 33, 23);

        buttonGroup4.add(r12);
        r12.setForeground(new java.awt.Color(255, 255, 255));
        r12.setText("L");
        jPanel1.add(r12);
        r12.setBounds(310, 770, 31, 23);

        jButton5.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton5.setText("Add to Cart");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(360, 770, 90, 25);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("JEANS & JEGGINGS");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 20, 380, 51);

        jButton6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton6.setText("Cart");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(680, 30, 80, 27);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code="", item_name = "", size = "", type = "", price = "", sql;
            
            sql = "select * from products where i_code=209;";
            System.out.print(sql);
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");
                
            }
            
            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);
            
            if (r1.isSelected())
                    size="S";
            if (r2.isSelected())
                    size="M";
             if (r3.isSelected())
                     size="L";
          
            sql = "Insert into cart Values("+i_code1+",'"+item_name+"','"+type+"','"+size+"',"+price1+");" ; 
         System.out.print(sql);
         st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        } 
JOptionPane.showMessageDialog(this,"This item has been added to your cart");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code="", item_name = "", size = "", type = "", price = "", sql;
            
            sql = "select * from products where i_code=210;";
            System.out.print(sql);
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");
                
            }
            
            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);
            
            if (r4.isSelected())
                    size="S";
            if (r5.isSelected())
                    size="M";
             if (r6.isSelected())
                     size="L";
          
            sql = "Insert into cart Values("+i_code1+",'"+item_name+"','"+type+"','"+size+"',"+price1+");" ; 
         System.out.print(sql);
         st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
JOptionPane.showMessageDialog(this,"This item has been added to your cart");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code="", item_name = "", size = "", type = "", price = "", sql;
            
            sql = "select * from products where i_code=211;";
            System.out.print(sql);
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");
                
            }
            
            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);
            
            if (r7.isSelected())
                    size="S";
            if (r8.isSelected())
                    size="M";
             if (r9.isSelected())
                     size="L";
          
            sql = "Insert into cart Values("+i_code1+",'"+item_name+"','"+type+"','"+size+"',"+price1+");" ; 
         System.out.print(sql);
         st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
JOptionPane.showMessageDialog(this,"This item has been added to your cart");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code="", item_name = "", size = "", type = "", price = "", sql;
            
            sql = "select * from products where i_code=212;";
            System.out.print(sql);
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");
                
            }
            
            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);
            
            if (r10.isSelected())
                    size="S";
            if (r11.isSelected())
                    size="M";
             if (r12.isSelected())
                     size="L";
          
            sql = "Insert into cart Values("+i_code1+",'"+item_name+"','"+type+"','"+size+"',"+price1+");" ; 
         System.out.print(sql);
         st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }  
JOptionPane.showMessageDialog(this,"This item has been added to your cart");// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code="", item_name = "", size = "", type = "", price = "", sql;
            
            sql = "select * from products where i_code=213;";
            System.out.print(sql);
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");
                
            }
            
            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);
            
            if (r13.isSelected())
                    size="S";
            if (r14.isSelected())
                    size="M";
             if (r15.isSelected())
                     size="L";
          
            sql = "Insert into cart Values("+i_code1+",'"+item_name+"','"+type+"','"+size+"',"+price1+");" ; 
         System.out.print(sql);
         st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        } 
JOptionPane.showMessageDialog(this,"This item has been added to your cart");// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
billing_section obj=new billing_section();
obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jeans_Jeggings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jeans_Jeggings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jeans_Jeggings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jeans_Jeggings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Jeans_Jeggings().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r13;
    private javax.swing.JRadioButton r14;
    private javax.swing.JRadioButton r15;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    // End of variables declaration//GEN-END:variables
}
