import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class Main_page extends javax.swing.JFrame {
Connection con = null;
Statement stmt = null;
ResultSet rs = null;
String e,p;
int c;
    /**
     * Creates new form Main
     */
    public Main_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JPasswordField();
        SignIn = new javax.swing.JButton();
        SignUp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(821, 514));
        setPreferredSize(new java.awt.Dimension(821, 514));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign In");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 140, 110, 33);

        jLabel2.setFont(new java.awt.Font("Mistral", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WALKER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 20, 160, 50);

        jLabel3.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Walk With Style");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 70, 140, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(370, 120, 0, 2);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 120, 830, 10);

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 190, 90, 20);

        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 260, 90, 20);

        t1.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(340, 220, 150, 30);
        getContentPane().add(t2);
        t2.setBounds(340, 290, 150, 30);

        SignIn.setText("Sign In");
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });
        getContentPane().add(SignIn);
        SignIn.setBounds(340, 340, 110, 23);

        SignUp.setText("Sign Up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp);
        SignUp.setBounds(340, 450, 110, 23);

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("New User?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 370, 100, 30);

        jLabel7.setFont(new java.awt.Font("Goudy Old Style", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Create your account now");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 400, 180, 20);

        jLabel8.setFont(new java.awt.Font("Goudy Old Style", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("to get access to our store.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 421, 190, 17);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/istockphoto-822609802-612x612.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 180, 290, 290);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_54fdeb3a8c72c.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(520, 180, 280, 290);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/862208.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 820, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
sign_up m;
        m = new sign_up();
        m.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpActionPerformed

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
main1 obj=new main1();
        try{
Class.forName("java.sql.DriverManager");
String pswd1="" ;
Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp","root","");
String emadd=t1.getText(),pswd=new String(t2.getPassword());
String sql="select password from signup where email_add ='"+emadd+"'";
Statement st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
//String pswd1=rs.getString("password");
//
if(!rs.next())
    JOptionPane.showMessageDialog(null,"No such Record");
else{
     pswd1=rs.getString("password");
System.out.println(pswd1);
}

if(pswd1.equals(pswd))
    obj.setVisible(true);
else 
    JOptionPane.showMessageDialog(null,"Incorrect password");
    


}
        catch(Exception e)
        {
JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
    }//GEN-LAST:event_SignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main_page().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignIn;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    // End of variables declaration//GEN-END:variables
}
