/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class Mens_Main extends javax.swing.JFrame {

    /**
     * Creates new form Mens_TopWear
     */
    public Mens_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        shirts_tshirts = new javax.swing.JMenuItem();
        jackets_coats = new javax.swing.JMenuItem();
        Sweater_sweatshirts = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenu();
        jeans = new javax.swing.JCheckBoxMenuItem();
        trousers = new javax.swing.JMenuItem();
        shorts = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem6.setText("jMenuItem6");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(814, 565));
        getContentPane().setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (2).png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(521, 206, 190, 270);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (1).png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(41, 276, 380, 130);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(41, 36, 340, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(481, 46, 275, 140);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows-vista-wallpaper-163.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 810, 500);

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("                                        TOP WEAR                                           ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        shirts_tshirts.setText("Shirts/T-shirts");
        shirts_tshirts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shirts_tshirtsMouseClicked(evt);
            }
        });
        shirts_tshirts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shirts_tshirtsActionPerformed(evt);
            }
        });
        jMenu1.add(shirts_tshirts);

        jackets_coats.setText("Jackets/Coats");
        jackets_coats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jackets_coatsMouseClicked(evt);
            }
        });
        jackets_coats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jackets_coatsActionPerformed(evt);
            }
        });
        jMenu1.add(jackets_coats);

        Sweater_sweatshirts.setText("Sweater/Sweatshirts");
        Sweater_sweatshirts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sweater_sweatshirtsMouseClicked(evt);
            }
        });
        Sweater_sweatshirts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sweater_sweatshirtsActionPerformed(evt);
            }
        });
        jMenu1.add(Sweater_sweatshirts);

        jMenuBar1.add(jMenu1);

        menu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu2.setText("                                     BOTTOM WEAR                                    ");
        menu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jeans.setText("Jeans");
        jeans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jeansMouseClicked(evt);
            }
        });
        jeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeansActionPerformed(evt);
            }
        });
        menu2.add(jeans);

        trousers.setText("Trousers");
        trousers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trousersMouseClicked(evt);
            }
        });
        trousers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trousersActionPerformed(evt);
            }
        });
        menu2.add(trousers);

        shorts.setText("Shorts");
        shorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortsActionPerformed(evt);
            }
        });
        menu2.add(shorts);

        jMenuBar1.add(menu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sweater_sweatshirtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sweater_sweatshirtsActionPerformed
Sweaters_sweatshirts  o3=new Sweaters_sweatshirts();
o3.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Sweater_sweatshirtsActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void shirts_tshirtsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shirts_tshirtsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_shirts_tshirtsMouseClicked

    private void shirts_tshirtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shirts_tshirtsActionPerformed
  Shirts_Tshirts o1=new Shirts_Tshirts();
o1.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_shirts_tshirtsActionPerformed

    private void jackets_coatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jackets_coatsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jackets_coatsMouseClicked

    private void jackets_coatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jackets_coatsActionPerformed
jackets_coats1  o2=new jackets_coats1();
o2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jackets_coatsActionPerformed

    private void Sweater_sweatshirtsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sweater_sweatshirtsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Sweater_sweatshirtsMouseClicked

    private void jeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeansActionPerformed
Mens_Jeans o4 =new Mens_Jeans();
o4.setVisible(true);;// TODO add your handling code here:
    }//GEN-LAST:event_jeansActionPerformed

    private void jeansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeansMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jeansMouseClicked

    private void trousersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trousersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_trousersMouseClicked

    private void trousersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trousersActionPerformed
mens_trousers o5=new mens_trousers();
o5.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_trousersActionPerformed

    private void shortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortsActionPerformed
Mens_shorts o6=new Mens_shorts();
o6.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_shortsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mens_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mens_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mens_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mens_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Mens_Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Sweater_sweatshirts;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem jackets_coats;
    private javax.swing.JCheckBoxMenuItem jeans;
    private javax.swing.JMenu menu2;
    private javax.swing.JMenuItem shirts_tshirts;
    private javax.swing.JMenuItem shorts;
    private javax.swing.JMenuItem trousers;
    // End of variables declaration//GEN-END:variables
}
