
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class mens_trousers extends javax.swing.JFrame {

    /**
     * Creates new form mens_trousers
     */
    public mens_trousers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        r7 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        r9 = new javax.swing.JRadioButton();
        r10 = new javax.swing.JRadioButton();
        r11 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        r13 = new javax.swing.JRadioButton();
        r14 = new javax.swing.JRadioButton();
        r15 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(847, 453));
        setMinimumSize(new java.awt.Dimension(847, 453));
        setPreferredSize(new java.awt.Dimension(847, 453));
        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(834, 830));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(834, 830));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(834, 830));

        jPanel1.setBackground(new java.awt.Color(118, 104, 104));
        jPanel1.setMaximumSize(new java.awt.Dimension(834, 830));
        jPanel1.setMinimumSize(new java.awt.Dimension(834, 830));
        jPanel1.setPreferredSize(new java.awt.Dimension(834, 830));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mt1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 90, 194, 259);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mt2.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 90, 199, 250);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mt3.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(540, 90, 190, 250);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mt4.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 460, 199, 259);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mt5.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(470, 460, 180, 260);

        jButton35.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton35.setText("Add to Cart");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton35);
        jButton35.setBounds(160, 400, 90, 25);

        jButton36.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton36.setText("Add to Cart");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton36);
        jButton36.setBounds(410, 400, 100, 25);

        jButton37.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton37.setText("Add to Cart");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton37);
        jButton37.setBounds(690, 400, 90, 25);

        jButton38.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton38.setText("Add to Cart");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton38);
        jButton38.setBounds(320, 780, 90, 25);

        jButton39.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton39.setText("Add to Cart");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton39);
        jButton39.setBounds(610, 780, 90, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Navy blue formal trousers");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(540, 350, 200, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Men's Black Formal Trousers");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 350, 210, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Men's Khaki Colour Formal Trousers");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 350, 250, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Men's Dark Grey Checked Formal Trousers");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 730, 290, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Men's Light Grey Formal Trousers");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(470, 730, 240, 20);

        buttonGroup1.add(r1);
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("S");
        jPanel1.add(r1);
        r1.setBounds(50, 400, 31, 23);

        buttonGroup1.add(r2);
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("M");
        jPanel1.add(r2);
        r2.setBounds(80, 400, 33, 23);

        buttonGroup1.add(r3);
        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.setText("L");
        jPanel1.add(r3);
        r3.setBounds(110, 400, 31, 23);

        buttonGroup2.add(r4);
        r4.setForeground(new java.awt.Color(255, 255, 255));
        r4.setText("S");
        jPanel1.add(r4);
        r4.setBounds(300, 400, 31, 23);

        buttonGroup2.add(r5);
        r5.setForeground(new java.awt.Color(255, 255, 255));
        r5.setText("M");
        jPanel1.add(r5);
        r5.setBounds(330, 400, 33, 23);

        buttonGroup2.add(r6);
        r6.setForeground(new java.awt.Color(255, 255, 255));
        r6.setText("L");
        jPanel1.add(r6);
        r6.setBounds(360, 400, 31, 23);

        buttonGroup3.add(r7);
        r7.setForeground(new java.awt.Color(255, 255, 255));
        r7.setText("S");
        jPanel1.add(r7);
        r7.setBounds(580, 400, 31, 23);

        buttonGroup3.add(r8);
        r8.setForeground(new java.awt.Color(255, 255, 255));
        r8.setText("M");
        jPanel1.add(r8);
        r8.setBounds(610, 400, 33, 23);

        buttonGroup3.add(r9);
        r9.setForeground(new java.awt.Color(255, 255, 255));
        r9.setText("L");
        jPanel1.add(r9);
        r9.setBounds(640, 400, 31, 23);

        buttonGroup4.add(r10);
        r10.setForeground(new java.awt.Color(255, 255, 255));
        r10.setText("S");
        jPanel1.add(r10);
        r10.setBounds(200, 780, 31, 23);

        buttonGroup4.add(r11);
        r11.setForeground(new java.awt.Color(255, 255, 255));
        r11.setText("M");
        jPanel1.add(r11);
        r11.setBounds(230, 780, 33, 23);

        buttonGroup4.add(r12);
        r12.setForeground(new java.awt.Color(255, 255, 255));
        r12.setText("L");
        jPanel1.add(r12);
        r12.setBounds(260, 780, 31, 23);

        buttonGroup5.add(r13);
        r13.setForeground(new java.awt.Color(255, 255, 255));
        r13.setText("S");
        jPanel1.add(r13);
        r13.setBounds(500, 780, 31, 23);

        buttonGroup5.add(r14);
        r14.setForeground(new java.awt.Color(255, 255, 255));
        r14.setText("M");
        jPanel1.add(r14);
        r14.setBounds(530, 780, 33, 23);

        buttonGroup5.add(r15);
        r15.setForeground(new java.awt.Color(255, 255, 255));
        r15.setText("L");
        jPanel1.add(r15);
        r15.setBounds(560, 780, 31, 23);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Price Rs 1900 Incl. of all taxes");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 370, 220, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Price Rs 2000 Incl. of all taxes");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(270, 370, 220, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Price Rs 1800 Incl. of all taxes");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(540, 370, 220, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Price Rs 1700 Incl. of all taxes");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(470, 750, 220, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Price Rs 1700 Incl. of all taxes");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(150, 750, 220, 20);

        jLabel6.setBackground(new java.awt.Color(255, 51, 51));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TROUSERS");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 10, 210, 60);

        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setText("Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(600, 30, 70, 25);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Size");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(460, 780, 30, 20);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Size");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(540, 400, 30, 20);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("Size");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(150, 780, 30, 20);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Size");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(270, 400, 30, 20);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("Size");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(20, 400, 30, 20);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 834, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
   try{
Class.forName("java.sql.DriverManager");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp","root","");
String i_code="",item_name="",sql ,size="",price="",type="";

sql="select * from products where i_code = 121;";
//System.out.print(sql);
Statement st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
if(!rs.next())
    JOptionPane.showMessageDialog(null,"no such record");
else{

i_code=rs.getString("i_code");
item_name=rs.getString("item_name");
price=rs.getString("price");
type=rs.getString("type");
}
int price1=Integer.parseInt(price);

int i_code1=Integer.parseInt(i_code);
if(r1.isSelected())
    size="S";
if(r2.isSelected())
    size="M";
if(r3.isSelected())
    size="L";
sql="insert into cart values ("+i_code1+", '"+item_name+"','"+type+"','"+size+"',"+price1+");";
System.out.print(sql);
st.executeUpdate(sql);


}    
catch(Exception e)
{  JOptionPane.showMessageDialog(null,"Error"+e.getMessage());

}JOptionPane.showMessageDialog(this,"This item has been added to your cart");      // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
try{
Class.forName("java.sql.DriverManager");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp","root","");
String i_code="",item_name="",sql ,size="",price="",type="";

sql="select * from products where i_code = 122;";
//System.out.print(sql);
Statement st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
if(!rs.next())
    JOptionPane.showMessageDialog(null,"no such record");
else{

i_code=rs.getString("i_code");
item_name=rs.getString("item_name");
price=rs.getString("price");
type=rs.getString("type");
}
int price1=Integer.parseInt(price);

int i_code1=Integer.parseInt(i_code);
if(r4.isSelected())
    size="S";
if(r5.isSelected())
    size="M";
if(r6.isSelected())
    size="L";
sql="insert into cart values ("+i_code1+", '"+item_name+"','"+type+"','"+size+"',"+price1+");";
System.out.print(sql);
st.executeUpdate(sql);


}    
catch(Exception e)
{  JOptionPane.showMessageDialog(null,"Error"+e.getMessage());

}JOptionPane.showMessageDialog(this,"This item has been added to your cart");          // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
try{
Class.forName("java.sql.DriverManager");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp","root","");
String i_code="",item_name="",sql ,size="",price="",type="";

sql="select * from products where i_code = 123;";
//System.out.print(sql);
Statement st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
if(!rs.next())
    JOptionPane.showMessageDialog(null,"no such record");
else{

i_code=rs.getString("i_code");
item_name=rs.getString("item_name");
price=rs.getString("price");
type=rs.getString("type");
}
int price1=Integer.parseInt(price);

int i_code1=Integer.parseInt(i_code);
if(r7.isSelected())
    size="S";
if(r8.isSelected())
    size="M";
if(r9.isSelected())
    size="L";
sql="insert into cart values ("+i_code1+", '"+item_name+"','"+type+"','"+size+"',"+price1+");";
System.out.print(sql);
st.executeUpdate(sql);


}    
catch(Exception e)
{  JOptionPane.showMessageDialog(null,"Error"+e.getMessage());

}JOptionPane.showMessageDialog(this,"This item has been added to your cart");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
try{
Class.forName("java.sql.DriverManager");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp","root","");
String i_code="",item_name="",sql ,size="",price="",type="";

sql="select * from products where i_code = 124;";
//System.out.print(sql);
Statement st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
if(!rs.next())
    JOptionPane.showMessageDialog(null,"no such record");
else{

i_code=rs.getString("i_code");
item_name=rs.getString("item_name");
price=rs.getString("price");
type=rs.getString("type");
}
int price1=Integer.parseInt(price);

int i_code1=Integer.parseInt(i_code);
if(r10.isSelected())
    size="S";
if(r11.isSelected())
    size="M";
if(r12.isSelected())
    size="L";
sql="insert into cart values ("+i_code1+", '"+item_name+"','"+type+"','"+size+"',"+price1+");";
System.out.print(sql);
st.executeUpdate(sql);


}    
catch(Exception e)
{  JOptionPane.showMessageDialog(null,"Error"+e.getMessage());

}JOptionPane.showMessageDialog(this,"This item has been added to your cart");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
try{
Class.forName("java.sql.DriverManager");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp","root","");
String i_code="",item_name="",sql ,size="",price="",type="";

sql="select * from products where i_code = 125;";
//System.out.print(sql);
Statement st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
if(!rs.next())
    JOptionPane.showMessageDialog(null,"no such record");
else{

i_code=rs.getString("i_code");
item_name=rs.getString("item_name");
price=rs.getString("price");
type=rs.getString("type");
}
int price1=Integer.parseInt(price);

int i_code1=Integer.parseInt(i_code);
if(r13.isSelected())
    size="S";
if(r14.isSelected())
    size="M";
if(r15.isSelected())
    size="L";
sql="insert into cart values ("+i_code1+", '"+item_name+"','"+type+"','"+size+"',"+price1+");";
System.out.print(sql);
st.executeUpdate(sql);


}    
catch(Exception e)
{  JOptionPane.showMessageDialog(null,"Error"+e.getMessage());

}JOptionPane.showMessageDialog(this,"This item has been added to your cart");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
billing_section obj=new billing_section();
obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mens_trousers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mens_trousers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mens_trousers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mens_trousers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new mens_trousers().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r13;
    private javax.swing.JRadioButton r14;
    private javax.swing.JRadioButton r15;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    // End of variables declaration//GEN-END:variables
}
