/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
import java.sql.*;
import javax.swing.JOptionPane;

public class Shirts_Tshirts extends javax.swing.JFrame {

    /**
     * Creates new form Shirts_Tshirts
     */
    public Shirts_Tshirts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        r7 = new javax.swing.JRadioButton();
        r11 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        r2 = new javax.swing.JRadioButton();
        r10 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        r12 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        r9 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        r8 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        jButton19 = new javax.swing.JButton();
        r4 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        addtocart = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        r3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        r6 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(855, 425));
        setMinimumSize(new java.awt.Dimension(855, 425));
        setPreferredSize(new java.awt.Dimension(855, 425));
        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(842, 752));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(842, 752));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(842, 752));

        jPanel1.setBackground(new java.awt.Color(118, 104, 104));
        jPanel1.setMaximumSize(new java.awt.Dimension(842, 752));
        jPanel1.setMinimumSize(new java.awt.Dimension(842, 752));
        jPanel1.setPreferredSize(new java.awt.Dimension(842, 752));
        jPanel1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel1MouseWheelMoved(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sh1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 100, 205, 225);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SHIRTS & T-SHIRTS");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 10, 410, 61);

        buttonGroup3.add(r7);
        r7.setForeground(new java.awt.Color(255, 255, 255));
        r7.setText("S");
        jPanel1.add(r7);
        r7.setBounds(330, 700, 33, 23);

        buttonGroup4.add(r11);
        r11.setForeground(new java.awt.Color(255, 255, 255));
        r11.setText("M");
        jPanel1.add(r11);
        r11.setBounds(630, 380, 33, 23);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price Rs 3000 Incl. of all taxes");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 670, 220, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mens  Blue Checked Shirt");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 330, 200, 20);

        buttonGroup1.add(r2);
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("M");
        jPanel1.add(r2);
        r2.setBounds(110, 380, 33, 23);

        buttonGroup4.add(r10);
        r10.setForeground(new java.awt.Color(255, 255, 255));
        r10.setText("S");
        jPanel1.add(r10);
        r10.setBounds(600, 380, 31, 23);

        buttonGroup1.add(r1);
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("S");
        jPanel1.add(r1);
        r1.setBounds(80, 380, 31, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t2.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(560, 100, 194, 220);

        buttonGroup4.add(r12);
        r12.setForeground(new java.awt.Color(255, 255, 255));
        r12.setText("L");
        jPanel1.add(r12);
        r12.setBounds(660, 380, 31, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sh3.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 430, 212, 220);

        buttonGroup3.add(r9);
        r9.setForeground(new java.awt.Color(255, 255, 255));
        r9.setText("L");
        jPanel1.add(r9);
        r9.setBounds(390, 700, 33, 23);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Size");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(290, 700, 30, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Price Rs 3000 Incl. of all taxes");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 350, 220, 20);

        buttonGroup3.add(r8);
        r8.setForeground(new java.awt.Color(255, 255, 255));
        r8.setText("M");
        jPanel1.add(r8);
        r8.setBounds(360, 700, 33, 23);

        buttonGroup2.add(r5);
        r5.setForeground(new java.awt.Color(255, 255, 255));
        r5.setText("M");
        jPanel1.add(r5);
        r5.setBounds(370, 380, 33, 23);

        jButton19.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton19.setText("Add to Cart");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(710, 380, 90, 25);

        buttonGroup2.add(r4);
        r4.setForeground(new java.awt.Color(255, 255, 255));
        r4.setText("S");
        jPanel1.add(r4);
        r4.setBounds(340, 380, 31, 23);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Size");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(40, 380, 30, 20);

        addtocart.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        addtocart.setText("Add to Cart");
        addtocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartActionPerformed(evt);
            }
        });
        jPanel1.add(addtocart);
        addtocart.setBounds(190, 380, 90, 25);

        jButton17.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton17.setText("Add to Cart");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(450, 380, 90, 25);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mens Black and White T-Shirt");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(560, 330, 210, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price Rs 3500 Incl. of all taxes");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 350, 210, 20);

        buttonGroup1.add(r3);
        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.setText("L");
        jPanel1.add(r3);
        r3.setBounds(140, 380, 30, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sh2.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 100, 192, 225);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Size");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(300, 380, 30, 20);

        buttonGroup2.add(r6);
        r6.setForeground(new java.awt.Color(255, 255, 255));
        r6.setText("L");
        jPanel1.add(r6);
        r6.setBounds(400, 380, 31, 23);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mens Olive Green Checked Shirt");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(300, 330, 220, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price Rs 1500 Incl. of all taxes");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(560, 350, 210, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mens Light Blue Shirt");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(290, 650, 160, 20);

        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setText("Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(620, 30, 70, 27);

        jButton15.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton15.setText("Add to Cart");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(440, 700, 90, 25);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Size");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(560, 380, 30, 20);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 840, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseWheelMoved

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code = "", item_name = "", sql, size = "", price = "", type = "";

            sql = "select * from products where i_code = 104;";
//System.out.print(sql);
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "no such record");
            } else {

                i_code = rs.getString("i_code");
                item_name = rs.getString("item_name");
                price = rs.getString("price");
                type = rs.getString("type");
            }
            int price1 = Integer.parseInt(price);

            int i_code1 = Integer.parseInt(i_code);
            if (r10.isSelected()) {
                size = "S";
            }
            if (r11.isSelected()) {
                size = "M";
            }
            if (r12.isSelected()) {
                size = "L";
            }
            sql = "insert into cart values (" + i_code1 + ", '" + item_name + "','" + type + "','" + size + "'," + price1 + ");";
            System.out.print(sql);
            st.executeUpdate(sql);


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());

        }
        JOptionPane.showMessageDialog(this, "This item has been added to your cart");       // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void addtocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code = "", item_name = "", sql, size = "", price = "", type = "";

            sql = "select * from products where i_code = 101;";
//System.out.print(sql);
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "no such record");
            } else {

                i_code = rs.getString("i_code");
                item_name = rs.getString("item_name");
                price = rs.getString("price");
                type = rs.getString("type");
            }
            int price1 = Integer.parseInt(price);

            int i_code1 = Integer.parseInt(i_code);
            if (r1.isSelected()) {
                size = "S";
            }
            if (r2.isSelected()) {
                size = "M";
            }
            if (r3.isSelected()) {
                size = "L";
            }
            sql = "insert into cart values (" + i_code1 + ", '" + item_name + "','" + type + "','" + size + "'," + price1 + ");";
            System.out.print(sql);
            st.executeUpdate(sql);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());

        }
        JOptionPane.showMessageDialog(this, "This item has been added to your cart");

    }//GEN-LAST:event_addtocartActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code = "", item_name = "", sql, size = "", price = "", type = "";

            sql = "select * from products where i_code = 102;";
//System.out.print(sql);
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "no such record");
            } else {

                i_code = rs.getString("i_code");
                item_name = rs.getString("item_name");
                price = rs.getString("price");
                type = rs.getString("type");
            }
            int price1 = Integer.parseInt(price);

            int i_code1 = Integer.parseInt(i_code);
            if (r4.isSelected()) {
                size = "S";
            }
            if (r5.isSelected()) {
                size = "M";
            }
            if (r6.isSelected()) {
                size = "L";
            }
            sql = "insert into cart values (" + i_code1 + ", '" + item_name + "','" + type + "','" + size + "'," + price1 + ");";
            System.out.print(sql);
            st.executeUpdate(sql);


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());

        }
        JOptionPane.showMessageDialog(this, "This item has been added to your cart");       // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        billing_section obj = new billing_section();
        obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code = "", item_name = "", sql, size = "", price = "", type = "";

            sql = "select * from products where i_code = 103;";
//System.out.print(sql);
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "no such record");
            } else {

                i_code = rs.getString("i_code");
                item_name = rs.getString("item_name");
                price = rs.getString("price");
                type = rs.getString("type");
            }
            int price1 = Integer.parseInt(price);

            int i_code1 = Integer.parseInt(i_code);
            if (r7.isSelected()) {
                size = "S";
            }
            if (r8.isSelected()) {
                size = "M";
            }
            if (r9.isSelected()) {
                size = "L";
            }
            sql = "insert into cart values (" + i_code1 + ", '" + item_name + "','" + type + "','" + size + "'," + price1 + ");";
            System.out.print(sql);
            st.executeUpdate(sql);


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());

        }
        JOptionPane.showMessageDialog(this, "This item has been added to your cart");       // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shirts_Tshirts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shirts_Tshirts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shirts_Tshirts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shirts_Tshirts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Shirts_Tshirts().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtocart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    // End of variables declaration//GEN-END:variables
}
