/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */import java.sql.*;
 import javax.swing.JOptionPane;
public class Tops_Tshirts extends javax.swing.JFrame {

    /**
     * Creates new form Tops_Tshirts
     */
    public Tops_Tshirts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        r4 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        r7 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        r9 = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        r10 = new javax.swing.JRadioButton();
        r11 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        r13 = new javax.swing.JRadioButton();
        r14 = new javax.swing.JRadioButton();
        r15 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(829, 460));
        setMinimumSize(new java.awt.Dimension(829, 460));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(840, 853));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(840, 853));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(840, 853));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(840, 853));
        jPanel1.setMinimumSize(new java.awt.Dimension(840, 853));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 853));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WT6.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 110, 209, 240);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WT1.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 110, 194, 250);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WT4.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 470, 194, 259);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WT5.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 110, 194, 250);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WT3.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(490, 470, 194, 259);

        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(87, 1615, 40, 14);

        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(320, 1615, 40, 14);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Women White Printed Top");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 360, 190, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Women Olive Green Solid Shirt Style Top");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(260, 370, 290, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Women Round Neck T-shirt");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(550, 370, 200, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" Price Rs. 799 (Incl. of all taxes)");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 380, 220, 20);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" Price Rs. 699 (Incl. of all taxes)");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(260, 390, 220, 20);

        jButton1.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 410, 90, 25);

        jButton2.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton2.setText("Add to Cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(420, 420, 90, 25);

        jButton3.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton3.setText("Add to Cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(700, 420, 90, 25);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Women Blue Self Design Peplum Top");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(490, 740, 260, 20);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Women Blue Solid Top");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(130, 740, 170, 20);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(" Price Rs. 899 (Incl. of all taxes)");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(490, 760, 220, 20);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(" Price Rs. 601 (Incl. of all taxes)");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(130, 760, 220, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Price Rs. 599 (Incl. of all taxes)");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(550, 390, 220, 20);

        jButton4.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton4.setText("Add to Cart");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(290, 790, 90, 25);

        jButton5.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton5.setText("Add to Cart");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(650, 790, 90, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Size");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 410, 40, 20);

        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("S");
        jPanel1.add(r1);
        r1.setBounds(60, 410, 31, 23);

        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("M");
        jPanel1.add(r2);
        r2.setBounds(90, 410, 33, 23);

        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.setText("L");
        jPanel1.add(r3);
        r3.setBounds(120, 410, 31, 23);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Size");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(270, 420, 30, 20);

        r4.setForeground(new java.awt.Color(255, 255, 255));
        r4.setText("S");
        jPanel1.add(r4);
        r4.setBounds(310, 420, 31, 23);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Size");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(550, 420, 30, 20);

        r7.setForeground(new java.awt.Color(255, 255, 255));
        r7.setText("S");
        jPanel1.add(r7);
        r7.setBounds(590, 420, 31, 23);

        r5.setForeground(new java.awt.Color(255, 255, 255));
        r5.setText("M");
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });
        jPanel1.add(r5);
        r5.setBounds(340, 420, 33, 23);

        r8.setForeground(new java.awt.Color(255, 255, 255));
        r8.setText("M");
        jPanel1.add(r8);
        r8.setBounds(620, 420, 33, 23);

        r6.setForeground(new java.awt.Color(255, 255, 255));
        r6.setText("L");
        jPanel1.add(r6);
        r6.setBounds(370, 420, 31, 23);

        r9.setForeground(new java.awt.Color(255, 255, 255));
        r9.setText("L");
        jPanel1.add(r9);
        r9.setBounds(650, 420, 31, 23);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Size");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(130, 790, 40, 20);

        r10.setForeground(new java.awt.Color(255, 255, 255));
        r10.setText("S");
        jPanel1.add(r10);
        r10.setBounds(170, 790, 31, 23);

        r11.setForeground(new java.awt.Color(255, 255, 255));
        r11.setText("M");
        jPanel1.add(r11);
        r11.setBounds(200, 790, 33, 23);

        r12.setForeground(new java.awt.Color(255, 255, 255));
        r12.setText("L");
        r12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r12ActionPerformed(evt);
            }
        });
        jPanel1.add(r12);
        r12.setBounds(230, 790, 31, 23);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Size");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(490, 790, 40, 20);

        r13.setForeground(new java.awt.Color(255, 255, 255));
        r13.setText("S");
        jPanel1.add(r13);
        r13.setBounds(530, 790, 31, 23);

        r14.setForeground(new java.awt.Color(255, 255, 255));
        r14.setText("M");
        jPanel1.add(r14);
        r14.setBounds(560, 790, 33, 23);

        r15.setForeground(new java.awt.Color(255, 255, 255));
        r15.setText("L");
        r15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r15ActionPerformed(evt);
            }
        });
        jPanel1.add(r15);
        r15.setBounds(590, 790, 31, 23);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("TOPS AND T-SHIRTS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 30, 420, 51);

        jButton6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton6.setText("Cart");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(630, 40, 80, 27);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r15ActionPerformed

    private void r12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r12ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code="", item_name = "", size = "", type = "", price = "", sql;
            
            sql = "select * from products where i_code=220;";
            System.out.print(sql);
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");
                
            }
            
            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);
            
            if (r13.isSelected())
                    size="S";
            if (r14.isSelected())
                    size="M";
             if (r15.isSelected())
                     size="L";
          
            sql = "Insert into cart Values("+i_code1+",'"+item_name+"','"+type+"','"+size+"',"+price1+");" ; 
         System.out.print(sql);
         st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }JOptionPane.showMessageDialog(this,"This item has been added to your cart");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code="", item_name = "", size = "", type = "", price = "", sql;
            
            sql = "select * from products where i_code=219;";
            System.out.print(sql);
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");
                
            }
            
            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);
            
            if (r10.isSelected())
                    size="S";
            if (r11.isSelected())
                    size="M";
             if (r12.isSelected())
                     size="L";
          
            sql = "Insert into cart Values("+i_code1+",'"+item_name+"','"+type+"','"+size+"',"+price1+");" ; 
         System.out.print(sql);
         st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }JOptionPane.showMessageDialog(this,"This item has been added to your cart");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code="", item_name = "", size = "", type = "", price = "", sql;
            
            sql = "select * from products where i_code=218;";
            System.out.print(sql);
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");
                
            }
            
            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);
            
            if (r7.isSelected())
                    size="S";
            if (r8.isSelected())
                    size="M";
             if (r9.isSelected())
                     size="L";
          
            sql = "Insert into products Values("+i_code1+",'"+item_name+"','"+type+"','"+size+"',"+price1+");" ; 
         System.out.print(sql);
         st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }JOptionPane.showMessageDialog(this,"This item has been added to your cart");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code="", item_name = "", size = "", type = "", price = "", sql;
            
            sql = "select * from products where i_code=216;";
            System.out.print(sql);
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");
                
            }
            
            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);
            
            if (r1.isSelected())
                    size="S";
            if (r2.isSelected())
                    size="M";
             if (r3.isSelected())
                     size="L";
          
            sql = "Insert into cart Values("+i_code1+",'"+item_name+"','"+type+"','"+size+"',"+price1+");" ; 
         System.out.print(sql);
         st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }JOptionPane.showMessageDialog(this,"This item has been added to your cart");

    }
//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaapp", "root", "");
            String i_code="", item_name = "", size = "", type = "", price = "", sql;
            
            sql = "select * from products where i_code=217;";
            System.out.print(sql);
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No such record exists");
            } else {
                price = rs.getString("price");
                i_code = rs.getString("i_code");
                type = rs.getString("type");
                item_name = rs.getString("item_name");
                
            }
            
            int price1 = Integer.parseInt(price);
            int i_code1 = Integer.parseInt(i_code);
            
            if (r4.isSelected())
                    size="S";
            if (r5.isSelected())
                    size="M";
             if (r6.isSelected())
                     size="L";
          
            sql = "Insert into cart Values("+i_code1+",'"+item_name+"','"+type+"','"+size+"',"+price1+");" ; 
         System.out.print(sql);
         st.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }JOptionPane.showMessageDialog(this,"This item has been added to your cart");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
billing_section obj=new billing_section();
obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tops_Tshirts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tops_Tshirts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tops_Tshirts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tops_Tshirts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Tops_Tshirts().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r13;
    private javax.swing.JRadioButton r14;
    private javax.swing.JRadioButton r15;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    // End of variables declaration//GEN-END:variables
}
